### ISSUE TITLE
Block quotes look weird

### ISSUE THREAD

**Issue by empezar** [Classic-Fortress/classic-fortress.github.io#28]
![sshot20150412094633](https://cloud.githubusercontent.com/assets/615926/7104797/eb1dd34a-e0f8-11e4-81a9-0d843ba300e0.png)

The code for this looks like this:

![sshot20150412094702](https://cloud.githubusercontent.com/assets/615926/7104798/ec5a7c90-e0f8-11e4-9f17-d29e160bae71.png)

**Comment by lindstrm** [comment]
thats pre and code, not blockqoute.
