### ISSUE TITLE
[code] looks like crap

### ISSUE THREAD

**Issue by empezar** [Classic-Fortress/classic-fortress.github.io#36]
![sshot20150415092335](https://cloud.githubusercontent.com/assets/615926/7153952/44b2ad40-e351-11e4-82cd-f992b7e543af.png)
![sshot20150415092435](https://cloud.githubusercontent.com/assets/615926/7153956/47f3b65c-e351-11e4-825a-ff7831199275.png)
![sshot20150415092418](https://cloud.githubusercontent.com/assets/615926/7153954/467252de-e351-11e4-92db-f80e9733a4aa.png)

**Comment by lindstrm** [comment]
Done in new version.
